[package]
name = "netcat-win-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
is_utf8 = "0.1"
anyhow = "1.0"
structopt = "0.3"

